# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_text', models.CharField(max_length=200)),
                ('cur_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('user_api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broadcast.GroupMeAPI')),
            ],
        ),
    ]
