# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_groupmegroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmeapi',
            name='cur_score',
        ),
    ]
