# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_remove_groupmeapi_cur_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMeGroup',
            new_name='Group',
        ),
    ]
