# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0005_auto_20160202_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupmeapi',
        ),
        migrations.DeleteModel(
            name='GroupMeAPI',
        ),
    ]
