# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0008_twitterkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterkeys',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
