# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0009_twitterkeys_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterkeys',
            name='screen_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
