# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-26 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ExamChoice',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='ExamQuestion',
        ),
    ]
