# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-26 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20151226_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamChoice',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='ExamQuestion',
            new_name='Problem',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='question_text',
            new_name='problem_text',
        ),
    ]
