# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-26 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20151226_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='problem',
        ),
    ]
