# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20151226_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
