# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-27 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20151226_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
