# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='problem',
            name='cur_score',
            field=models.IntegerField(default=0),
        ),
    ]
