# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20151227_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
    ]
