# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224163721 on 2015-12-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_problem_num_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='num_problems',
            field=models.IntegerField(default=1),
        ),
    ]
